### ISSUE TITLE
Drop down for existing wallets

### ISSUE THREAD

**Issue by elktamer** [utkarsh009/heliota#1]
I'm getting a "wallet does not exist" message when I enter the what I think the correct name of the wallet is. 

Adding a dropdown list of the available wallets would remove the chance that this is caused by a typo.

**Comment by utkarsh009** [comment]
https://github.com/utkarsh009/heliota/commit/1ed477e6adc0bce19002963453c5fe815f2127a3 should fix it. Can you please test it and let me know if this breaks any other functionality? :smile: :+1:

**Comment by elktamer** [comment]
That worked great, but I get an error after that:

./heliota.sh: 14: ./heliota.sh: Syntax error: "(" unexpected

I'm running this on raspbian, so maybe the sh version is a bit different. I'll fix it and then post the change. Maybe it'll work on everything else too.

e: it wasn't really an error. Raspbian uses "dash" for "sh" instead of "bash", so running the script with bash works as expected

**Comment by utkarsh009** [comment]
https://github.com/utkarsh009/heliota/commit/4e20a62fd1f41320d35232b3a40f7b63a51b667e should fix it for now. But, bash is not available by default on BSD systems, so I had to use sh. There are multiple ways for a more universal fix. I'll see which one is the best suited, and push an update later, or maybe just leave it as it is. Thanks for reporting it. I am closing this issue for now. :+1: 
**PS: Please open a new issue for a new bug from next time. It makes issue tracking easier. :smile:**
